### group by customer. Show first 7
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true | all(
    group(customer)
    max(3)
    each(
      output(count())
    )
  )"
}

### order by count descending
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true | all(
    # group by item
    group(customer)
    # order by count descending
    order(-count())
    max(7)
    # show the actual count value for each group
    each(
        output(count())
    )
  )"
}

### use total $$$ instead of count. But output count as well
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true | all(
    group(customer)
    order(-sum(price))
    each(
        output(sum(price))
        output(count())
    )
  )"
}

### sales by day, by customer
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true | all(
    group(time.date(date))
    each(
        output(sum(price))
        output(count())

        # within each bucket, take all orders
        all(
            # group them by customer
            group(customer)

            # order by revenue descending, like we did before
            order(-sum(price))
            each(
                output(sum(price) as(revenue_per_customer_per_day))
                output(count())
            )
        )
    )
  )"
}

### frequent customers, but also show 7 sample orders
# --> limit 0 to not show order list below
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true limit 0 | all(
    # group by customer as before
    group(customer)
    order(-count())
    each(
        output(count())

        # top 3 orders for each item
        max(7)

        # show the actual order (i.e. summary)
        each(
            output(summary())
        )
    )
  )"
}

### customer cardinality (HyperLogLog++)
POST https://<mTLS_ENDPOINT_DNS_GOES_HERE>/search/
Content-Type: application/json

{
  "yql": "select * from purchase where true | all(
    group(customer)
    output(count())
  )"
}
